koxudaxi/poetry-pycharm-plugin

- .github/workflows/CI.yml
- .github/workflows/publish.yml
- gradle/wrapper/gradle-wrapper.properties
> - update jdk version

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryPackageManagerListener.kt
- src/com/koxudaxi/poetry/PyPoetryPackageManager.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/24
> improve handling sdk

- resources/META-INF/plugin.xml
This PR remove invalid contents in `Open Project` menu.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/34
> Remove a invalid content in Open Project menu

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryExtrasLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryInterpreterinspection.kt
- src/com/koxudaxi/poetry/PoetryPackageRequirementsInspection.kt
- src/com/koxudaxi/poetry/PyAddPoetryPanel.kt
- src/com/koxudaxi/poetry/poetry.kt
This PR improves handling invalid interpreters.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/36
> improve handling invalid interpreter

- README.md
- docs/index.md
- resources/META-INF/plugin.xml
- resources/messages/PoetryBundle.properties
- src/com/jetbrains/python/sdk/add/PyAddExistingVirtualEnvPanel.kt
- src/com/koxudaxi/poetry/PoetryBundle.java
- src/com/koxudaxi/poetry/PyAddExistingPoetryEnvPanel.kt
- src/com/koxudaxi/poetry/PyAddNewPoetryPanel.kt
- src/com/koxudaxi/poetry/PyAddPoetrySdkProvider.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/45
> Support adding existing env

- docs/development.md
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/55
> update contribution document

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/poetry.kt
This PR adds python version for environment name
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/76
> Add python version for environment name

- README.md
- docs/index.md
- resources/META-INF/only-toml.xml
- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryRunScript.kt
- src/com/koxudaxi/poetry/PoetryScriptsLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryToolWindow.kt
This PR supports script.
https://python-poetry.org/docs/pyproject/#scripts
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/80
> support script

- README.md
- docs/index.md
- resources/META-INF/only-toml.xml
- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryVersionInspection.kt
- src/com/koxudaxi/poetry/PyPoetryPackageManager.kt
- src/com/koxudaxi/poetry/poetry.kt
- testData/Poetry/parsePoetryShoOutdated/show-outdated.txt
- testSrc/com/koxudaxi/poetry/PoetryTest.kt
This PR adds to a version inspection.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/79
> [WIP] add a version inspection

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryRunScript.kt
- src/com/koxudaxi/poetry/PoetryScriptsLineMarkerContributor.kt
This PR supports running `scripts` on `RunConfiguration`.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/80
> Support running scripts with RunConfiguration 

- build.gradle
- resources/META-INF/plugin.xml
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/111
> change max target version to 2020.3

- resources/META-INF/only-toml.xml
- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/PoetryPackageVersion.html
This PR fixes the inspection config.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/114
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/115
> Fix broken inspection config

- build.gradle
- resources/META-INF/plugin.xml
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/118
> Fix invalid build target version for IntelliJ

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetrySdkProvider.kt
- src/com/koxudaxi/poetry/PyAddExistingPoetryEnvPanel.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/125
> Fix wrong icon for system interpreter

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PyPoetryPackageManager.kt
- testData/PyPoetryPackageManager/parsePoetryInstallDryRun/dry-run-result.txt
- testData/PyPoetryPackageManager/parsePoetryInstallDryRun1_0/dry-run-result.txt
- testData/PyPoetryPackageManager/parsePoetryInstallDryRun1_1/dry-run-result.txt
- testSrc/com/koxudaxi/poetry/PoetryTestCase.kt
- testSrc/com/koxudaxi/poetry/PyPoetryPackageManagerTest.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/126
> Fix wrong warning for installed packages

- README.md
- build.gradle
- docs/index.md
- docs/install.md
- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryPySdkConfigurationCollector.kt
- src/com/koxudaxi/poetry/PyAddNewPoetryFromFilePanel.kt
- src/com/koxudaxi/poetry/PyPoetrySdkConfiguration.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/140
> Support pycharm 2020 3

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/158
> Support poetry lock with  no update

- build.gradle
- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryExtrasLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryScriptsLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryVersionInspection.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/169
> Support Toml plugin version 0.2.140.3644-202

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryExtrasLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryScriptsLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryVersionInspection.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/172
> Support Toml plugin version 0.2.139.3615-203 or earlier version

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/175#issuecomment-775259884
> Fix broken dependency on Toml plugin

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/175
> Change command timeout to 30 sec

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PyAddNewPoetryPanel.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/197
> [1.1.x] Remove checking poetry executable

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/223
> Update an error dialog to the same as  the dialog of pipenv

- build.gradle
- resources/META-INF/plugin.xml
- testSrc/com/jetbrains/python/fixtures/PythonMockSdk.java
-　https://github.com/koxudaxi/poetry-pycharm-plugin/issues/233
> Support PyCharm EAP 212.*

- resources/META-INF/plugin.xml
- src/com/koxudaxi/poetry/PoetryExtrasLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryScriptsLineMarkerContributor.kt
- src/com/koxudaxi/poetry/PoetryVersionInspection.kt
- src/com/koxudaxi/poetry/poetry.kt
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/262
> Fix toml header problem
